[package]
name = "elimination_engine_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-engine = "0.1.2"
komrend = { path = "komrend" }
bmp_reader = { path = "bmp_reader" }